### ISSUE TITLE
io.UnsupportedOperation: IOStream has no fileno.

### ISSUE THREAD

**Issue by PhE** [tbenthompson/cppimport#1]
Get the following error when I tried to run the somecode example.
The `import importcpp ` statment went fine.
I get the error on the `import somecode` line :

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 890, in _find_spec
AttributeError: 'CppFinder' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda/lib/python3.5/site-packages/cppimport/import_hook.py", line 30, in stdchannel_redirected
    oldstdchannel = os.dup(stdchannel.fileno())
  File "/miniconda/lib/python3.5/site-packages/ipykernel/iostream.py", line 306, in fileno
    raise UnsupportedOperation("IOStream has no fileno.")
io.UnsupportedOperation: IOStream has no fileno.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda/lib/python3.5/site-packages/cppimport/import_hook.py", line 241, in find_module
    build_plugin(fullname, filepath)
  File "/miniconda/lib/python3.5/site-packages/cppimport/import_hook.py", line 187, in build_plugin
    with stdchannel_redirected(sys.stdout, os.devnull):
  File "/miniconda/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/miniconda/lib/python3.5/site-packages/cppimport/import_hook.py", line 36, in stdchannel_redirected
    if oldstdchannel is not None:
UnboundLocalError: local variable 'oldstdchannel' referenced before assignment

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-73fe0814eaed> in <module>()
----> 1 import somecode

ImportError: No module named 'somecode'
```

**Comment by tbenthompson** [comment]
Thanks for the bug report. I just pushed a fix that should solve the problem. I redirect stdout and stderr during the build (unless you've run `cppimport.set_quiet(False)` ), but the code assumed that stdout and stderr were set to file handles. For some reason, your IPython installation is redirecting stdout to an IOStream object already. Anyway, everything should work now.
