### ISSUE TITLE
Using cppimport with Python3.5

### ISSUE THREAD

**Issue by kirit93** [tbenthompson/cppimport#13]
When I run example provided in the read me, I get the following error:

```
>>> import cppimport
>>> somecode = cppimport.imp('somecode')
Traceback (most recent call last):
  File "/Users/kirit/anaconda/envs/python-prosodizer/lib/python3.5/site-packages/mako/lexer.py", line 209, in decode_raw_stream
    text = text.decode(parsed_encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 67: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/anaconda/envs/python-prosodizer/lib/python3.5/site-packages/cppimport/importer.py", line 57, in imp
    template_and_build(filepath, module_data)
  File "/Users/kirit/anaconda/envs/python-prosodizer/lib/python3.5/site-packages/cppimport/importer.py", line 42, in template_and_build
    templating.run_templating(module_data)
  File "/Users/kirit/anaconda/envs/python-prosodizer/lib/python3.5/site-packages/cppimport/templating.py", line 38, in run_templating
    tmpl = mako.template.Template(filename = filepath, lookup = lookup)
  File "/Users/kirit/anaconda/envs/python-prosodizer/lib/python3.5/site-packages/mako/template.py", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "/Users/kirit/anaconda/envs/python-prosodizer/lib/python3.5/site-packages/mako/template.py", line 416, in _compile_from_file
    filename)
  File "/Users/kirit/anaconda/envs/python-prosodizer/lib/python3.5/site-packages/mako/template.py", line 705, in _compile_text
    generate_magic_comment=template.disable_unicode)
  File "/Users/kirit/anaconda/envs/python-prosodizer/lib/python3.5/site-packages/mako/template.py", line 685, in _compile
    node = lexer.parse()
  File "/Users/kirit/anaconda/envs/python-prosodizer/lib/python3.5/site-packages/mako/lexer.py", line 224, in parse
    self.filename)
  File "/Users/kirit/anaconda/envs/python-prosodizer/lib/python3.5/site-packages/mako/lexer.py", line 215, in decode_raw_stream
    0, 0, filename)
mako.exceptions.CompileException: Unicode decode operation of encoding 'ascii' failed in file '/Users/kirit/ZeroLabs/GRU/pybind_gru/somecode.cpp' at line: 0 char: 0
```

I believe this is because my Python system version is 2.7 and my Anaconda python version is 3.5. 
I'm not sure how to fix this issue. 

Any help would be deeply appreciated!

**Comment by myd7349** [comment]
cppimport uses `Mako` template engine internally to render your input file (it is `somecode.cpp` in your case) to a purely C++ source file that `pybind11` can understand.

In your case, it seems that `Mako` failed to detect the encoding of your source file. Maybe you can save `somecode.cpp` with some other encodings.

**Comment by tbenthompson** [comment]
Yes. This appears to be an issue with the file you created (or maybe with Mako) and not with cppimport.

I don't think that the difference in version between your anaconda python and your system python version is an issue so long as each python installation is accessing its respective packages folder.
