### ISSUE TITLE
README example fails with ImportError on OSX

### ISSUE THREAD

**Issue by Janislav** [tbenthompson/cppimport#4]
Problem
=======

When i try to run the example from the README i end up with the following trace

```
Python 2.7.10 (default, Jul 10 2015, 09:06:15)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cppimport
>>> import somecode
Traceback (most recent call last):
  File "/private/tmp/pycpp/env/lib/python2.7/site-packages/cppimport/import_hook.py", line 230, in find_module
    build_plugin(fullname, filepath)
  File "/private/tmp/pycpp/env/lib/python2.7/site-packages/cppimport/import_hook.py", line 149, in build_plugin
    pybind11.get_include(),
  File "/private/tmp/pycpp/env/lib/python2.7/site-packages/pybind11/__init__.py", line 9, in get_include
    locations.distutils_scheme('pybind11', *args, **kwargs)['headers'])
AttributeError: 'module' object has no attribute 'distutils_scheme'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named somecode
```

Any idea? Seems like it could also a bug in pybind11 :/. The cpp code is available in the same directory.

Thanks in advance, it's a cool thing :).

**Comment by tbenthompson** [comment]
I'm guessing this is a pip version problem. Could you try upgrading pip to the latest version and running again? If that succeeds, could you also send me your original pip version, so I can start tracking down exactly which version of pip is needed for cppimport? Thanks!

**Comment by Janislav** [comment]
Original PIP Version is pip 1.3.1. I upgradet pip and tried again but now i'am getting another error:
```
Traceback (most recent call last):
  File "/private/tmp/pycpp/env/lib/python2.7/site-packages/cppimport/import_hook.py", line 230, in find_module
    build_plugin(fullname, filepath)
  File "/private/tmp/pycpp/env/lib/python2.7/site-packages/cppimport/import_hook.py", line 178, in build_plugin
    setuptools.setup(**setuptools_args)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 969, in run_command
    log.info("running %s", command)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/log.py", line 40, in info
    self._log(INFO, msg, args)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/log.py", line 30, in _log
    stream.write('%s\n' % msg)
TypeError: unicode argument expected, got 'str'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named somecode
````
My pip version is now pip 8.1.2. I also reinstalled cppimport. I thought it maybe  it has something todo with setuptools, but upgrading dosen't solve the error. By the way i'am running on python 2.7. Is that a problem?

**Comment by tbenthompson** [comment]
I think this is a python 2 bug that was just fixed by a pull request: https://github.com/tbenthompson/cppimport/pull/5
I just uploaded a bug fix version to pypi, so reinstall and make sure you have version 0.0.11. Let me know if that solves the problem!

**Comment by Janislav** [comment]
That solved the problem thanks a lot :). I see you can also import directly from .so files which makes it very fast. Cool stuff!
